### ISSUE TITLE
Missing file files/production.yaml

### ISSUE THREAD

**Issue by jocelynj** [fflorent/ansible-peertube#4]
It looks like this file is required by this code:
```
- name: Copy production.yaml
  copy:
    src: files/production.yaml
    dest: /var/www/peertube/config/production.yaml
    owner: peertube
    group: peertube
    mode: 0644
```

Should I take this file from peertube checkout ?
